### ISSUE TITLE
Improve UI 

### ISSUE THREAD

**Issue by TabberApps2024** [TabberApps2024/Tabber-Goals#3]
### Feature Description

Change the UI so the following UI Controls are easier to see: 

- [x] **Panels**
    - [x] Darker border
    - [x] More contrasting backgrounds
--------------------------------------------------------------------
- [x] **Buttons**
    - [x] Darker border
    - [x] Bigger text/icon
    - [x] Bigger size
    - [x] Background accent colour for add goal button

### Windows Version

All Above

**Comment by jayden-w-2007** [comment]
- [x]  **Panels**
     - [x]  Darker border
     - [x]  More contrasting backgrounds
- [x]  **Buttons**
     - [x]  Darker border
     - [x]  Bigger text/icon
     - [x]  Bigger size
     - [x]  Background accent colour for add goal button
- [x] **Other**
     - [x] Bigger margins
